### ISSUE TITLE
DbHandler Logger issue

### ISSUE THREAD

**Issue by devgc** [devgc/EventMonkey#12]
Appears that logger has issues across multiple processes when wanting to roll over to a new log.

```
Traceback (most recent call last):
  File "C:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process
Logged from file DbHandler.py, line 126
```

**Comment by devgc** [comment]
Changed db logger from logging.handlers.RotatingFileHandler to logging.FileHandler
